# Generated by Django 4.2.8 on 2024-02-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty_fields', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Faculty Name')),
                ('acceptance', models.PositiveSmallIntegerField(verbose_name='Acceptance Number')),
                ('grant', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Grant Score')),
                ('contract', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Contract Score')),
                ('education_forms', models.ManyToManyField(to='faculty_fields.education_form', verbose_name='Education Forms')),
                ('first_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_subject_relation', to='faculty_fields.subject', verbose_name='First Subject')),
                ('second_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_subject_relation', to='faculty_fields.subject', verbose_name='Second Subject')),
                ('tuition_languages', models.ManyToManyField(to='faculty_fields.tuition_language', verbose_name='Tuition Languages')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
