# Generated by Django 4.2.8 on 2024-02-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduname', models.CharField(max_length=32, verbose_name='eduname')),
            ],
            options={
                'verbose_name': 'Education_form',
                'verbose_name_plural': 'Education_forms',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=32, verbose_name='subname')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Tuition_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=32, verbose_name='language')),
            ],
            options={
                'verbose_name': 'Tuition_language',
                'verbose_name_plural': 'Tuition_languages',
            },
        ),
    ]
